# Cable sous-marin


## Questions théoriques


1) La loi des grands nombres nous autorise à estimer l'espérance conditionnelle par la moyenne empirique de simulations conditionnelles

2) La densité de du vecteur des composantes de Z correspondant aux points de discrétisation sans observation , connaissant les valeurs prises par les composantes aux sites d'obersvation est:

\begin{align}
f_{Z|X=x}(z)=\frac{1}{(2\pi)^{k/2}\sqrt{det(CS_{Z})}}exp(-\frac{1}{2}(z-g(x))^{t}CS_{Z}^{-1}(z-g(x))
\end{align}

On en déduit que  la variable aéatoire Y|Z=z est gaussienne d'épérance:


\begin{align} 
m_{Z|X=x}=m_{X}-C_{Z,X}C_{X}^{-1}(X-m_{x})
\end{align}

et de matrice de covariance

\begin{align}
CS_{Z}=C_{Z}-C_{Z,X}C_{X}^{-1}C_{X,Z}
\end{align}

3) Si Y=(Y1,Y2,...,Yp) est un vecteur de composantes gaussiennes d'indépendantes toutes d'espérance nulle et de variance 1 ( on notera C la matrice de covariance de ce vecteur), alors le vecteur Z= m +RY est gaussien d'espérance m et de matrice de covariance C


En effet Z est gaussiencommme combinaison linéaire de variables aléatoires gaussiennes,


\begin{align}
E(Z)=E(m+LY)=m
\end{align}

4)\begin{align}


## Code


In [2]:
import sys
!{sys.executable} -m pip install numpy 



In [3]:

import numpy as np
from numpy.linalg import inv
import math 
import matplotlib.pyplot as plt


ModuleNotFoundError: No module named 'matplotlib'

In [4]:
#Discrétisation
A=0
B=500
N=101 #Nombre de points de discrétisation
Delta=(B-A)/(N-1)
discretization_indexes=np.arange(N)
discretization = discretization_indexes*Delta

#Paramètres du modèle
mu=-5
a = 50
sigma2 = 12

#Données 
observation_indexes = (0, 20, 40, 60, 80, 100)
depth = np.array([0,-4, -12.8, -1, -6.5, 0])

#indices des composantes correspondant aux observations et aux composantes non observées
unknow_indexes=list(set(discretization_indexes)-set(observation_indexes))



Q1)

In [5]:
def  covariance (h, a ,sigma2):
    return sigma2*math.exp(-abs(h)/a)

def covariance_matrice(Mh, a, sigma2):
    lignesMh=len(Mh)
    colonnesMh=len(Mh[0])
    M=np.zeros((lignesMh, colonnesMh))
    for i in range(lignesMh):
        for j in range(colonnesMh):
            M[i][j]=covariance(Mh[i][j], a , sigma2)
    return M


Q2) Calcul de la matrice de distance

In [6]:
def matrice_distance (e,p):
    
    mh=np.zeros((p, p))
    for  i in range(p):
        for j in range (p):
            mh[i][j]=abs(i-j)*e #distance positive
    return mh

#cas de l'exo
M=matrice_distance(Delta, N)


Q3)Matrice de covariance de Z

In [7]:
C=covariance_matrice(M, a, sigma2)

Q4) Extraction des 3 matrices de covariance

In [13]:
#extraction de la matrice de covariance entre les observations
C_obs=np.zeros((6,6))
p=0
k=0
for i in observation_indexes:
    for j in observation_indexes:
        C_obs[p][k]=C[i][j]
        k+=1
    k=0
    p+=1

C_obs


array([[1.20000000e+01, 1.62402340e+00, 2.19787667e-01, 2.97450261e-02,
        4.02555153e-03, 5.44799157e-04],
       [1.62402340e+00, 1.20000000e+01, 1.62402340e+00, 2.19787667e-01,
        2.97450261e-02, 4.02555153e-03],
       [2.19787667e-01, 1.62402340e+00, 1.20000000e+01, 1.62402340e+00,
        2.19787667e-01, 2.97450261e-02],
       [2.97450261e-02, 2.19787667e-01, 1.62402340e+00, 1.20000000e+01,
        1.62402340e+00, 2.19787667e-01],
       [4.02555153e-03, 2.97450261e-02, 2.19787667e-01, 1.62402340e+00,
        1.20000000e+01, 1.62402340e+00],
       [5.44799157e-04, 4.02555153e-03, 2.97450261e-02, 2.19787667e-01,
        1.62402340e+00, 1.20000000e+01]])

In [16]:
#extraction de la matrice de covariance entre les inconnues
C_inc=np.zeros((95,95))
p=0
k=0
for i in unknow_indexes:
    for j in unknow_indexes:
        C_inc[p][k]=C[i][j]
        k+=1
    k=0
    p+=1

C_inc


array([[1.20000000e+01, 1.08580490e+01, 9.82476904e+00, ...,
        8.12744838e-04, 7.35401941e-04, 6.65419193e-04],
       [1.08580490e+01, 1.20000000e+01, 1.08580490e+01, ...,
        8.98221959e-04, 8.12744838e-04, 7.35401941e-04],
       [9.82476904e+00, 1.08580490e+01, 1.20000000e+01, ...,
        9.92688787e-04, 8.98221959e-04, 8.12744838e-04],
       ...,
       [8.12744838e-04, 8.98221959e-04, 9.92688787e-04, ...,
        1.20000000e+01, 1.08580490e+01, 9.82476904e+00],
       [7.35401941e-04, 8.12744838e-04, 8.98221959e-04, ...,
        1.08580490e+01, 1.20000000e+01, 1.08580490e+01],
       [6.65419193e-04, 7.35401941e-04, 8.12744838e-04, ...,
        9.82476904e+00, 1.08580490e+01, 1.20000000e+01]])

In [12]:
#extraction de la matrice de covariante entre les observations et les inconnues
C_incobs=np.zeros((95,6))
p=0
k=0
for i in unknow_indexes:
    for j in observation_indexes:
        if i<j:
            C_incobs[p][k]=C[i][j]
        k+=1
    k=0
    p+=1
    
C_incobs #soit C(Z,X)


array([[0.00000000e+00, 1.79482343e+00, 2.42902937e-01, 3.28733378e-02,
        4.44892249e-03, 6.02096185e-04],
       [0.00000000e+00, 1.98358666e+00, 2.68449262e-01, 3.63306569e-02,
        4.91681975e-03, 6.65419193e-04],
       [0.00000000e+00, 2.19220229e+00, 2.96682318e-01, 4.01515855e-02,
        5.43392619e-03, 7.35401941e-04],
       [0.00000000e+00, 2.42275822e+00, 3.27884669e-01, 4.43743646e-02,
        6.00541720e-03, 8.12744838e-04],
       [0.00000000e+00, 2.67756192e+00, 3.62368601e-01, 4.90412573e-02,
        6.63701244e-03, 8.98221959e-04],
       [0.00000000e+00, 2.95916357e+00, 4.00479240e-01, 5.41989713e-02,
        7.33503313e-03, 9.92688787e-04],
       [0.00000000e+00, 3.27038152e+00, 4.42598009e-01, 5.98991269e-02,
        8.10646530e-03, 1.09709078e-03],
       [0.00000000e+00, 3.61433054e+00, 4.89146448e-01, 6.61987730e-02,
        8.95902970e-03, 1.21247282e-03],
       [0.00000000e+00, 3.99445300e+00, 5.40590429e-01, 7.31609588e-02,
        9.90125908e-03, 

Q5)On calcule l'espérance conditionnelle

In [14]:
#calcul de l'espérance conditionnelle
esp_obs=[mu for i in range(6)] #vecteur espérance des observations
esp_inc=[mu for i in range(95)] # vecteur espérance des inconnues
C_obsinv=inv(C_obs) #on calcul l'inverse de la matrice de covariance des observables
produit_intermediaire=np.dot(C_incobs,C_obsinv) #on effectue un calcul intermédiarre pour calculer le produit entre C(Z,X) et C(X)-1
produit_intermediaire

esp_conditionelle=esp_inc-np.dot(produit_intermediaire,(depth-esp_obs)) #d'après la formule établie dans la partie théorique

Q6) On calcule la matrice de variance conditionnelle

In [17]:
C_obsinc=np.transpose(C_incobs) #soit C(X,Z)
C_condi=C_inc-np.dot(produit_intermediaire, C_obsinc) #calcul de la variance conditionnelle

In [18]:
taille_Ccondi= len(C_condi)
diago_Ccondi=[C_condi[i][i] for i in range(taille_Ccondi)]
xp=unknow_indexes
plt.plot(xp,diapo_Ccondi)
plt.grid()
plt.show()

NameError: name 'plt' is not defined

Q7) ?

In [20]:
R=np.linalg.cholesky(C_inc) #calcul de la matrice R

#simulation Y
from scipy.stats import norm
Y=norm.rvs(size=N-5) #donne le vecteur avec N variable centrée réduite 

#simulation Z
Z=esp_conditionelle +np.dot(R,Y)


ModuleNotFoundError: No module named 'scipy'

Q8)

In [ ]:
def longueur_cable(pas, Z):
    l=0
    for i in range(len(Z)):
        l+=(pas**2+(Z[i+1]-Z[i])**2)**(1/2) #d'après la formule donnée dans l'énoncé
    return l     

Q9) d'après la formule de L* donnée dans l'énoncé

In [ ]:
def L_etoile(n): #avec n le nombre de simulation
    p=0
    for i in range(n):
        Z1=#simuler Z1
        p+=longueur_cable(Delta, Z1)
    return p/n

##non fini

Q10)

In [ ]:
nb=[i for i in range(1, 500)] #nombre de simulation entre 1 et 499
Mn=[L_etoile(n) for n in nb ]
plt.plot(n,Mn)
plt.grid()
plt.show()